### ISSUE TITLE
Encoding issues when trying to send message

### ISSUE THREAD

**Issue by hoehermann** [hoehermann/wxpyWha#10]
Occurs after conversation window was automatically opened upon receival of media message from previously unknown contact. yowsup version is jlguardi@6ea1319.

    Traceback (most recent call last):
      File "gui/ConversationFrame.py", line 163, in onSendButtonClick
        sent = self.client.sendMessage(outgoingMessage)
      File "whastack.py", line 53, in sendMessage
        interface.sendMessage(outgoingMessage)
      File "whalayer.py", line 94, in sendMessage
        self.toLower(outgoingMessage)
      File "yowsup/layers/__init__.py", line 79, in toLower
        self.__lower.send(data)
      File "yowsup/layers/__init__.py", line 192, in send
        s.send(data)
      File "yowsup/layers/__init__.py", line 130, in send
        send(entity)
      File "yowsup/layers/protocol_messages/layer.py", line 15, in sendMessageEntity
        self.entityToLower(entity)
      File "yowsup/layers/__init__.py", line 134, in entityToLower
        self.toLower(entity.toProtocolTreeNode())
      File "yowsup/layers/__init__.py", line 79, in toLower
        self.__lower.send(data)
      File "yowsup/layers/axolotl/layer.py", line 126, in send
        self.handlePlaintextNode(node)
      File "yowsup/layers/axolotl/layer.py", line 194, in handlePlaintextNode
        messageData = self.serializeToProtobuf(node) if v2 else node.getChild("body").getData()
      File "yowsup/layers/axolotl/layer.py", line 528, in serializeToProtobuf
        return self.serializeTextToProtobuf(node)
      File "yowsup/layers/axolotl/layer.py", line 536, in serializeTextToProtobuf
        m.conversation = node.getChild("body").getData()
      File "/usr/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 471, in field_setter
        self._fields[field] = type_checker.CheckValue(new_value)
      File "/usr/lib/python2.7/dist-packages/google/protobuf/internal/type_checkers.py", line 103, in CheckValue
        raise TypeError(message)
    TypeError: u'Okay, got it. :)' has type <type 'unicode'>, but expected one of: (<type 'str'>,)

Sending the same message after restarting the application works.

**EDIT:** Update: Problem persists when launching through X-Forwarding. It is somehow tied to the GTK wxPython frontend.

**Comment by hoehermann** [comment]
Sending a message containing a non-ascii character like ü or ß results in a disconnect:

    Traceback (most recent call last):
      File "whastack.py", line 59, in start
        self.stack.loop()
      File "yowsup/stacks/yowstack.py", line 195, in loop
        asyncore.loop(*args, **kwargs)
      File "/usr/lib/python2.7/asyncore.py", line 216, in loop
        poll_fun(timeout, map)
      File "/usr/lib/python2.7/asyncore.py", line 156, in poll
        read(obj)
      File "/usr/lib/python2.7/asyncore.py", line 87, in read
        obj.handle_error()
      File "/usr/lib/python2.7/asyncore.py", line 83, in read
        obj.handle_read_event()
      File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
        self.handle_read()
      File "yowsup/layers/network/layer.py", line 102, in handle_read
        self.receive(data)
      File "yowsup/layers/network/layer.py", line 110, in receive
        self.toUpper(data)
      File "yowsup/layers/__init__.py", line 75, in toUpper
        self.__upper.receive(data)
      File "yowsup/layers/stanzaregulator/layer.py", line 29, in receive
        self.processReceived()
      File "yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
        self.toUpper(oneMessageData)
      File "yowsup/layers/__init__.py", line 75, in toUpper
        self.__upper.receive(data)
      File "yowsup/layers/auth/layer_crypt.py", line 65, in receive
        self.toUpper(payload)
      File "yowsup/layers/__init__.py", line 75, in toUpper
        self.__upper.receive(data)
      File "yowsup/layers/coder/layer.py", line 35, in receive
        self.toUpper(node)
      File "yowsup/layers/__init__.py", line 75, in toUpper
        self.__upper.receive(data)
      File "yowsup/layers/logger/layer.py", line 14, in receive
        self.toUpper(data)
      File "yowsup/layers/__init__.py", line 75, in toUpper
        self.__upper.receive(data)
      File "yowsup/layers/axolotl/layer.py", line 134, in receive
        if not self.processIqRegistry(protocolTreeNode):
      File "yowsup/layers/__init__.py", line 155, in processIqRegistry
        successClbk(protocolTreeNode, originalIq)
      File "yowsup/layers/axolotl/layer.py", line 192, in <lambda>
        self._sendIq(entity, lambda a, b: self.onGetKeysResult(a, b, self.processPendingMessages), self.onGetKeysError)
      File "yowsup/layers/axolotl/layer.py", line 660, in onGetKeysResult
        processPendingFn(jid)
      File "yowsup/layers/axolotl/layer.py", line 170, in processPendingMessages
        self.handlePlaintextNode(messageNode)
      File "yowsup/layers/axolotl/layer.py", line 197, in handlePlaintextNode
        ciphertext = sessionCipher.encrypt(messageData)
      File "/usr/local/lib/python2.7/dist-packages/axolotl/sessioncipher.py", line 41, in encrypt
        paddedMessage = bytearray(paddedMessage.encode())
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xdf' in position 9: ordinal not in range(128)

**Update:** This one should be fixed in a0746a5.

**Comment by hoehermann** [comment]
Resolved with transition to Python 3 in cf93115.
